//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamaceyDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Operation_Damage_Item
    {
        public int dmg_item_id { get; set; }
        public Nullable<int> dmg_item_quntity { get; set; }
        public Nullable<System.DateTime> dmg_item_expDate { get; set; }
        public string dmg_B_It_note { get; set; }
        public Nullable<int> Med_id { get; set; }
        public Nullable<int> dmg_op_id { get; set; }
        public Nullable<int> store_place_id { get; set; }
    
        public virtual T_Medician T_Medician { get; set; }
        public virtual T_OPeration_Damage T_OPeration_Damage { get; set; }
        public virtual T_Store_Placees T_Store_Placees { get; set; }
    }
}
