//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamaceyDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Roles
    {
        public int Id { get; set; }
        public string keyy { get; set; }
        public Nullable<bool> value { get; set; }
        public int User_Id { get; set; }
    
        public virtual T_Users T_Users { get; set; }
    }
}
